coverage:
  status:
    project: #add everything under here, more options at https://docs.codecov.com/docs/commit-status
      default:
        # basic
#        target: auto #default
        target: 80%
#        threshold: 0%
        threshold: 5%
        base: auto

#coverage:
#  status:
#    project:
#      default:
#        target: 75%  # Overall project coverage target
#        threshold: 1%  # Allowable decrease before failure
#    patch:
#      default:
#        target: 80%  # Require at least 80% coverage for new/modified lines
#        threshold: 0%  # No decrease allowed for patch coverage

comment:                  #this is a top-level key
  layout: " diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: false        # [true :: must have a base report to post]
  require_head: true       # [true :: must have a head report to post]
  hide_project_coverage: false # [true :: only show coverage on the git diff aka patch coverage]]